sudo: required
dist: precise
language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-[0-9a-f]{8}
